# Generated by Django 4.2.11 on 2024-04-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraccionesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficial',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
