# Generated by Django 4.2.11 on 2024-04-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraccionesApp', '0002_alter_oficial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
