# Generated by Django 4.2.11 on 2024-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraccionesApp', '0003_alter_persona_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraccion',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
